### ISSUE TITLE
"logging" key value in config is not optional

### ISSUE THREAD

**Issue by 37ch4** [ryanwinchester/netsuite-php#16]
Removing "logging" from the config array yields an error:

ErrorException in NetSuiteClient.php line 265:
Undefined index: logging

Using example code 'Searching for customers who emails start with "j"'

Read me states it is optional. I set to false to satisfy logSoapCall

**Comment by ryanwinchester** [comment]
Let me know if this fixes your problem?

You'll need to use `dev-master`
