### ISSUE TITLE
2016_2 Release

### ISSUE THREAD

**Issue by jonathan-bird** [ryanwinchester/netsuite-php#19]
I'm just about to start using this. Looks awesome, thanks for your work!

Is there any way to have this upgraded to the latest 2016_2 release?

If not, what's the best process to upgrade it?

**Comment by trm42** [comment]
There seems to be `utilities`-directory in this repo which has `separate_classes.php`. It probably does what you want. How about try that and create PR if it works as intended? :)

**Comment by Ian410** [comment]
I ran the separate_classes.php and it does indeed work as intended.  The only issue I had with it is that it does not delete classes that were previously created and removed in the newer version.  In the case of 2016_1 -> 2016_2 there were only two or three removals so not a big deal; I determined which to remove by comparing the classmap.php changes.

**Comment by balintk** [comment]
I went ahead and created a pull request: #20. Hopefully it's helpful.

**Comment by ryanwinchester** [comment]
Yes, thanks :)
