### ISSUE TITLE
Examplify Transactions and Search

### ISSUE THREAD

**Issue by xewl** [ryanwinchester/netsuite-php#22]
It might be helpful for many of us to examplify the Sales/Purchase Orders (iow: Transactions)
And the difference between Basic & Advanced search.

This, as their examples are insufficient and pretty basic ~~hidden behind some kind of permission-scope, which I can't reach at the moment. eg. https://netsuite.custhelp.com/app/answers/detail/a_id/39177 should have some examples (Given to me by mail) but I get directed to the suite backend itself after logging in.~~
[Found out that I have to go via the backend › support › SuiteAnswers]

**Comment by wkolcz-UMHS** [comment]
I would love to see how to attach a SalesOrderItem(s) to the SalesOrder object to create a new Sales Order

**Comment by aadityamundhalia** [comment]
How can i call a list classs example recordList

**Comment by jrebs** [comment]
Fixed in #53 

I hope the samples are sufficient. As I mentioned, I don't think it's appropriate to document the NetSuite web services here, only the library usage. For example, things like the differences between types of searches can be taken from NetSuite's own docs.
