### ISSUE TITLE
SearchCustomStringField Class Missing

### ISSUE THREAD

**Issue by oabreu** [ryanwinchester/netsuite-php#26]
Hi,if i want to do a search based on a custom field,according to this example [https://stackoverflow.com/questions/18203226/search-customer-by-custom-field-in-netsuite](https://stackoverflow.com/questions/18203226/search-customer-by-custom-field-in-netsuite) I should be able to do it using a class called SearchCustomStringField , but i can't find that class here, i only have SearchCustomField Class, and is not the same,since this one doesn't have operator or searchValue. Is this class missing on this package? thanks

**Comment by nopolabs** [comment]
NetSuite\Classes\SearchStringCustomField ?

**Comment by oabreu** [comment]
oh ok,i was looking for SearchCustomStringField like in that sample,not SearchStringCustomField ,thanks
