### ISSUE TITLE
Using Country class..

### ISSUE THREAD

**Issue by amitfts** [ryanwinchester/netsuite-php#28]
We have to pass Country in Address. I have not seen any example or way to passing it.
Can you please help us.

```
$billAdd = new Address();
//$ctry = new Country();
//$ctry::$paramtypesmap=['name'=>$ctry::_unitedArabEmirates];
//$billAdd->country = $ctry;
$billAdd->addr1 ='Test add 1';
$billAdd->addr2 ='Test add 2';
$billAdd->city ='Dubai';

```

**Comment by Ian410** [comment]
Set it using the constant from the class

`$billAdd->country = \NetSuite\Classes\Country::_unitedArabEmirates;`

**Comment by amitfts** [comment]
Thanks Ian Coast.
It works..
I was trying to create a Country object..
