### ISSUE TITLE
Upgrade to 2017.1.2

### ISSUE THREAD

**Issue by neclimdul** [ryanwinchester/netsuite-php#30]
Evaluating this I noticed NetSuite has an updated toolkit. Don't know what sort of changes there are but thought I would open an issue and bring it to your attention.

http://www.netsuite.com/portal/developers/resources/suitetalk-sample-applications.shtml

**Comment by jrebs** [comment]
If accepted, PR #40 will update the package to 2018_2, but you can try it out right away by specifying the PR branch or using my fork in the meantime.
