### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by adrian-stein** [ryanwinchester/netsuite-php#31]
I am using 2017_1 and if you look at [this URL](http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_1/schema/record/salesorder.html) it shows all the fields available to a sales order

Some of these are missing in this module. Specially 'salesRep' and 'shipMethod'  I need which are not present. Is there any reason why or are you able to add them or is there a way I can extend the module and add them?

They appear to be properties on the salesOrder object but there are no RecordTypes for these 2 and I get the following error when trying to send to NetSuite

> [User Error] Uncaught SoapFault: org.xml.sax.SAXException: salesRep is not a legal value for {urn:types.core_2017_1.platform.webservices.netsuite.com}RecordType Line 94 in C:\vendor\ryanwinchester\netsuite-php\src\NetSuiteClient.php

Thanks

**Comment by ryanwinchester** [comment]
Looks to me like they are both `RecordRef` types.

**Comment by adrian-stein** [comment]
You are correct but you need to pass a type when creating the record ref as below.

```
        $sales_order = new SalesOrder();

        $sales_rep = new RecordRef();
        $sales_rep->type = 'salesRep';
        $sales_rep->internalId = 1234;

        $sales_order->salesRep = $sales_rep;
```

When I set that type to 'salesRep' as the type it comes back with that error. I assume as it is not an allowed type. A 'recordRefs' Type is a "RecordType" as seen below and in that class there is no constant for salesRep or shipMethod. 

```
class RecordRef extends BaseRef {
    public $internalId;
    public $externalId;
    public $type;
    static $paramtypesmap = array(
        "internalId" => "string",
        "externalId" => "string",
        "type" => "RecordType",
    );
}
```

Or am I missing something?

**Comment by adrian-stein** [comment]
I  am contacted NetSuite and they have solved the issue. It appears that when adding a salesRep to an order the RecordRef type to use is 'employee' and you dont add a type for shipMethod.

That doenst make much sense to me and I was not able to find any info on it around the web.

**Comment by ryanwinchester** [comment]
> That doenst make much sense to me and I was not able to find any info on it around the web.

i.e. typical for anything to do with NetSuite ;)
