### ISSUE TITLE
SoapFault: You are not requesting the correct data center for your company! Please correct the host in the URL.

### ISSUE THREAD

**Issue by soniakhil1992** [ryanwinchester/netsuite-php#37]
SoapFault: You are not requesting the correct data center for your company! Please correct the host in the URL. in SoapClient->__soapCall() (line 90 of \vendor\ryanwinchester\netsuite-php\src\NetSuiteClient.php).

Tried with these host values 
https://webservices.netsuite.com
https://webservices.na1.netsuite.com

Still getting same error. 

Can you please help me ? 

And one more favor Please, I want to test connection is established or not, How can I do that , Can you provide any code example ? 

Thanks.

**Comment by Ian410** [comment]
Sounds like you have most everything correct except the URLs, to do that you need to run the getDataCenterUrls() function located in https://github.com/ryanwinchester/netsuite-php/blob/master/src/NetSuiteService.php#L355.  I suspect once you get the correct URL you'll be fine.

That will return both the SOAP url you should be using.  After the last NetSuite release, they changed how you can access their service, this new method results in way faster web services calls but a little less intuitive.

That getDataCenterUrls should return something to the effect of 

> [restDomain] => https://XXXXXX-dc1.restlets.api.netsuite.com
> [webservicesDomain] => https://XXXXXX-dc1.suitetalk.api.netsuite.com
> [systemDomain] => https://system.netsuite.com

You would then use webservices domain url for all your SOAP calls.  Each environment you work in (prod, staging, etc) will have a different URL.

**Comment by soniakhil1992** [comment]
Thank you for help.

Is there any parameter or any function is there for checking that token-based authentication is success. 

So we can show the flag that login is success or not.


Thanks

**Comment by Ian410** [comment]
I would use the getServerTime call to test.  If it succeeds you'll get the NetSuite time.  If it fails it will throw an exception "Soap Error: Invalid login attempt."

**Comment by soniakhil1992** [comment]
Oh ok. Thank you for quick response. 👍

**Comment by soniakhil1992** [comment]
Hello @Ian410 

What should be the parameter in getServerTime and getDataCenterUrls ? 

I have tried using config values as well as service values. 

But I got this error 

**Argument 1 passed to NetSuite\NetSuiteService::getServerTime() must be an instance of NetSuite\Classes\GetServerTimeRequest, array given, called in \modules\netsuite\src\Form\netsuiteTestForm.php on line 75**

Thanks.

**Comment by Ian410** [comment]
The error tells you what it expects, instantiate an instance of NetSuite\Classes\GetServerTimeRequest and pass it to getServerTime.

**Comment by soniakhil1992** [comment]
Ok got it, Thanks
