### ISSUE TITLE
2 factor auth in 2018_2

### ISSUE THREAD

**Issue by aadityamundhalia** [ryanwinchester/netsuite-php#38]
Hi Ryan,
Can we please update this package as the netsuite is updating 2 factor auth with 2018_2.

Thanks

**Comment by eortega** [comment]
Hello Ryan;

Is in your plan to update library to use toolkit 2018.* or above ?

If not, how can I help you to this happen ?

Regards !

**Comment by jrebs** [comment]
@eortega I have just submitted PR #40 which is an updated copy using the 2018_2 classes (2019_1 is still not available yet as a toolkit). I've only done some basic tests so far with no problems, so feel free to give it a try through the PR checkout. It's also available in my own fork if that's easier, until Ryan accepts this PR (or makes his own update).

**Comment by aadityamundhalia** [comment]
> 
> 
> @eortega @aadityamundhalia I have just submitted PR #40 which is an updated copy using the 2018_2 classes (2019_1 is still not available yet as a toolkit). I've only done some basic tests so far with no problems, so feel free to give it a try through the PR checkout. It's also available in my own fork if that's easier, until Ryan accepts this PR (or makes his own update).

Thanks Mate will definitely look into it. Appreciate your efforts.

**Comment by ryanwinchester** [comment]
> @eortega @aadityamundhalia I have just submitted PR #40 which is an updated copy using the 2018_2 classes

Merged, thanks @jrebs .
