### ISSUE TITLE
GetDataCenterUrlsRequest

### ISSUE THREAD

**Issue by twangi** [ryanwinchester/netsuite-php#39]
Thank you for this project, it is just what I was looking for to embed NetSuite functionality into my own MVC project.

I had to make one alteration to your `NetSuiteClient::__construct` to avoid getting the following error:

> Type: SoapFault
> Message: Incorrect data center requested! The data center you are requesting is not the data center where your account is hosted. To obtain the correct URL for your request, please use the SOAP getDataCenterUrls operation.

I added 5 lines to the end of your constructor:

```
    public function __construct($config, $options = array(), $client = null)
    {

        $this->config = $config;
        $options = $this->createOptions($this->config, $options);
        $wsdl = $this->createWsdl($this->config);
        $this->client = $client ?: new SoapClient($wsdl, $options);

        // Fetch and set Data Center URL to use
        $params = new \NetSuite\Classes\GetDataCenterUrlsRequest();
        $params->account = $config['account'];
        $response = $this->getDataCenterUrls($params);
        $webservicesDomain = $response->getDataCenterUrlsResult->dataCenterUrls->webservicesDomain;
        $this->client->__setLocation($webservicesDomain . "/services/NetSuitePort_" . $config['endpoint']);

    }
```

**Comment by hounded** [comment]
should really make that a pull request

**Comment by franciscoisidori** [comment]
+1 for the pull request

**Comment by jrebs** [comment]
Fixed in the new release
