### ISSUE TITLE
2015_2 and 2016_1

### ISSUE THREAD

**Issue by pixelpaulaus** [ryanwinchester/netsuite-php#4]
any chance of getting this for the 2015_2 release and the soon to be released 2016_1
as i believe the initial config/connection is different

**Comment by ryanwinchester** [comment]
Yeah I should get around to that soon, thanks.

**Comment by ryanwinchester** [comment]
I use their PHP toolkits to make this, and I can't get 2015_2 as it's a broken link on their website.

**Comment by jhcaiced** [comment]
@ryanwinchester I got a copy of the 2015_2 toolkit file from that page, maybe this can help:  https://www.dropbox.com/s/njrww4zvh2y6wub/PHPToolkit_2015_2.zip?dl=0

**Comment by ryanwinchester** [comment]
Thanks @jhcaiced

**Comment by skylord123** [comment]
Anything I can do to help with 2016 version? I am using this for one of the companies I work for. Would love to help out if I can.

Also, any reason why NetSuite does their classes in one big file under the global namespace? Was hoping they would fix that in the 2016 release.
