### ISSUE TITLE
BaseRef is an abstract type and cannot be instantiated

### ISSUE THREAD

**Issue by kahnage** [ryanwinchester/netsuite-php#42]
Hi,
I am try to get this working in a laravel app (laravel 5.8). Having trouble getting the soap call to execute successfully. I am not sure if this is due to using php7+ ? I have been able to get this working with php5.6 (in our legacy code environment), but I am really keen to get this working with Laravel. 

![image](https://user-images.githubusercontent.com/3316850/54879571-5b622200-4e32-11e9-9673-088bd0ab9a07.png)  
Error triggered in: NetSuiteClient.php  
![image](https://user-images.githubusercontent.com/3316850/54879575-687f1100-4e32-11e9-9b05-1afaf38f62e1.png)    

I have just followed the 'Retrieving a customer record' from the readme.  

Any assistance is greatly appreciated.

**Comment by ryanwinchester** [comment]
are you trying to instantiate `BaseRef` directly?

**Comment by kahnage** [comment]
Hi.
Thanks for getting back to me.

I am doing exactly what you have in your example:  
```
$service = new NetSuiteService($config);

        $service->setSearchPreferences(false, 20);

        $request = new GetRequest();
        $request->baseRef = new RecordRef();
        $request->baseRef->internalId = "12";
        $request->baseRef->type = "customer";

        $getResponse = $service->get($request);
```  
The following is a dump of all the params for the `$response = $this->client->__soapCall($operation, array($parameter), null, $this->soapHeaders)`  function Inside NetSuiteClient.php  (Before __soapCall executes)
```
array:3 [▼
  0 => "get"
  1 => array:1 [▼
    0 => GetRequest {#1179 ▼
      +baseRef: RecordRef {#1180 ▼
        +internalId: "12"
        +externalId: null
        +type: "customer"
        +name: null
      }
    }
  ]
  2 => array:2 [▼
    "searchPreferences" => SoapHeader {#1178 ▼
      +"namespace": "ns"
      +"name": "searchPreferences"
      +"data": SearchPreferences {#1177 ▶}
      +"mustUnderstand": false
    }
    "tokenPassport" => SoapHeader {#1183 ▼
      +"namespace": "ns"
      +"name": "tokenPassport"
      +"data": TokenPassport {#1181 ▶}
      +"mustUnderstand": false
    }
  ]
]
```

**Comment by kahnage** [comment]
Hi.

Sorted. Because I had installed this package manually, the class mappings were wrong. 

Thanks again.
