### ISSUE TITLE
I need to disable 2FA to work?

### ISSUE THREAD

**Issue by Webysther** [ryanwinchester/netsuite-php#56]
TBA + RESTLet is supported?

https://docs.oracle.com/cloud/latest/netsuitecs_gs/NSATH/NSATH.pdf (page 9/10 Authentication Matrix item 2)

**Comment by jrebs** [comment]
Can you be more specific? I use two-factor on my personal netsuite login and I also use it for web services connections with this library. Did you grant your user WS permissions?

**Comment by Webysther** [comment]
> Can you be more specific? I use two-factor on my personal netsuite login and I also use it for web services connections with this library. Did you grant your user WS permissions?

You answer my question, thank you.
