### ISSUE TITLE
Example - get contacts for customer

### ISSUE THREAD

**Issue by jbardnz** [ryanwinchester/netsuite-php#57]
Hi there,

Do you have any examples on how I can get all of the contacts for a customer. I think I need to use this mapping table: https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2019_2/odbc/record/companycontactmap.html

But I am unsure how to do that with this library?

**Comment by jrebs** [comment]
Sorry, if I knew about using these sorts of records I'd offer what help I can, but I don't and your question seems to me like you don't quite know the requests you need to make in the first place, which is not really specific to this library. If you figure out the requests you need to make and have a more specific question feel free to open a new issue, but at the moment I think what you probably want is a consultant with NS Web Services expertise. Figuring out what needs to be send back and forth between you and netsuite is the hard part. Once you know what you're looking for, doing it with this library is fairly trivial.
