### ISSUE TITLE
How to get Invoices PDF by Internal ID with Netsuite API?

### ISSUE THREAD

**Issue by thosieucoi** [ryanwinchester/netsuite-php#59]
I'm trying to get Invoices PDF by Internal ID with Netsuite API. Would anyone works with this before? I'm appreciated for your help.
Below is my code to get invoices list

```
        $transactionSearch = new SearchEnumMultiSelectField();
        $transactionSearch->operator = "anyOf";
        $transactionSearch->searchValue = array('_invoice');

        $search = new TransactionSearchBasic();
        $search->type = $transactionSearch;

        $request = new SearchRequest();
        $request->searchRecord = $search;

        $searchResponse = $this->netsuite_service->search($request);
```

**Comment by jrebs** [comment]
Sorry, but I don't think github issues are a good place to do application support for NetSuite web services. If you don't have a NetSuite developer available to help with your query, I would suggest using stackoverflow or similar to find solutions to what you're trying to accomplish. If you make it far enough that you have a functional example that doesn't seem to be doing what is expected specific to this library, feel free to open another issue and we can look at something more concrete.
