### ISSUE TITLE
failed to load external entity

### ISSUE THREAD

**Issue by dmcmillin** [ryanwinchester/netsuite-php#69]
using 2019_1 endpoint. 

Fatal error: Uncaught SoapFault exception: [HTTP] Unable to parse URL in /home/apide/public_html/vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.php:194
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', '/services/NetSu...', 'search', 1, 0)
#1 /home/apide/public_html/vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.php(194): SoapClient->__soapCall('search', Array, NULL, Array)
#2 /home/apide/public_html/vendor/ryanwinchester/netsuite-php/src/NetSuiteService.php(125): NetSuite\NetSuiteClient->makeSoapCall('search', Object(NetSuite\Classes\SearchRequest))
#3 /home/apide/public_html/startswithj.php(40): NetSuite\NetSuiteService->search(Object(NetSuite\Classes\SearchRequest))
#4 {main}
  thrown in /home/apide/public_html/vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.php on line 194

`<?php
require 'vendor/autoload.php';

use NetSuite\NetSuiteService;

$config = array(
   // required -------------------------------------
   "endpoint"       => "2019_1",
"host"     => "https://webservices.netsuite.com",
   "account"        => "41320xx-xxx",
   "consumerKey"    => "708e8eaa448f319e8680146aa576ed2629d551b1e3aa732f5c36eb2",
   "consumerSecret" => "9f34f222296081683f3f32029a91e970f169e7b769201bf533af1a7986",
   "token"          => "241b059f917c6d8b24207fc1ebfb675d743fabb9eb70fc570eb19717",
   "tokenSecret"    => "a89d37d3f3fe15e10583d59a9c7dce1607150235e7432db8dc371281",
   // optional -------------------------------------
   "signatureAlgorithm" => 'sha256', // Defaults to 'sha256'
//"logging"  => true,
   //"log_path" => "/home/apide/public_html"
);

$service = new NetSuiteService($config);

use NetSuite\Classes\SearchStringField;
use NetSuite\Classes\CustomerSearchBasic;
use NetSuite\Classes\SearchRequest;

$service->setSearchPreferences(false, 20);

$emailSearchField = new SearchStringField();
$emailSearchField->operator = "startsWith";
$emailSearchField->searchValue = "j";

$search = new CustomerSearchBasic();
$search->email = $emailSearchField;

$request = new SearchRequest();
$request->searchRecord = $search;

$searchResponse = $service->search($request);

if (!$searchResponse->searchResult->status->isSuccess) {
    echo "SEARCH ERROR";
} else {
    $result = $searchResponse->searchResult;
    $count = $result->totalRecords;
    $records = $result->recordList;

    echo $count . " records were found.";
}
`

**Comment by jrebs** [comment]
I would suggest trying this using an account specific domain. I might be wrong but I think NetSuite may have dropped support for the https://webservices.netsuite.com method in recent releases. I'm not sure because I've been using account-specific domains for a while now.

You'll probably want to use the suitetalk domain for your account which you can obtain from the netsuite UI in the following section:

![image](https://user-images.githubusercontent.com/4203789/81013776-95ad3980-8e10-11ea-852a-741fbb06fa82.png)

**Comment by dmcmillin** [comment]
now its saying invalid login even though that information is correct and it works on postman without any issues.
