### ISSUE TITLE
Code to push a custom record using the script id of custom record type

### ISSUE THREAD

**Issue by parthvora-parkstreet** [ryanwinchester/netsuite-php#70]
Hello,

I'm not able to push a custom typed record using script id of that record type. It is working with the internal id of the record type.

Code with internal id:
```
        $rRef             = new \NetSuite\Classes\RecordRef;
        $rRef->internalId = 9;

        $nsBrandObj          = new \NetSuite\Classes\CustomRecord;
        $nsBrandObj->recType = $rRef;

        $nsBrandObj->name = 'Brand 2';

        $request         = new AddRequest();
        $request->record = $nsBrandObj;
        $addResponse     = $netSuiteApi->add($request);
```

What I would like to use here is script id of that record type which is **customrecord_cs_brand**

Any help would be appreciated.

Thanks

**Comment by jrebs** [comment]
I have never worked with custom records before (only custom fields), but did you try using something like this?

```php
$nsBrandObj = new \NetSuite\Classes\CustomRecord;
$nsBrandObj->scriptId = 'customrecord_cs_brand';
$nsBrandObj->name = 'Brand 2';

$request         = new AddRequest();
$request->record = $nsBrandObj;
$addResponse     = $netSuiteApi->add($request);
```

**Comment by jrebs** [comment]
Hi Parth, getting no response for three weeks on these tickets, I'm going to close them both and assume problem resolved.
