### ISSUE TITLE
Code to delete a Custom record from the NetSuite

### ISSUE THREAD

**Issue by parthvora-parkstreet** [ryanwinchester/netsuite-php#71]
Hello,

Here is the code I'm using to delete a custom record from the NetSuite:

```
        $rf = new RecordRef;
        $rf->internalId = 3348;
        $dr = new DeletionReason;
        $dr->deletionReasonCode = $rf;
        $request = new DeleteRequest();
        $request->deletionReason = $dr;
        $response = $netSuiteApi->delete($request);
```

But is giving this error:
**org.xml.sax.SAXException: {urn:core_2019_2.platform.webservices.netsuite.com}BaseRef is an abstract type and cannot be instantiated**

Any help would be appreciated.

Thanks

**Comment by jrebs** [comment]
It seems to me like you're passing a deletion reason but you're not actually indicating a record that you want to delete. I presume you also want to assign `$request->baseRef = <someObject>`.

**Comment by jrebs** [comment]
Hi Parth, getting no response for three weeks on these tickets, I'm going to close them both and assume problem resolved.
