### ISSUE TITLE
v2015.2.1 Does not include app_id config setting in client.

### ISSUE THREAD

**Issue by ctrogers** [ryanwinchester/netsuite-php#8]
We have been using the v2015.1.2 version of the netsuite-php package without issue for over a year.  I am now in the process of evaluating the v2015.2.1 version of the netsuite-php package and ran into an issue.  The NetSuite API requires an application id to be sent within the passport Soap header when using an endpoint >= 2015_2.

The client class within the v2015.2.1 does not allow the application id to be set.  As it stands the current version is not usable without modification or creating a fork to correct the client class.

Is this a known issue and do you plan on correcting it?

Thanks for your help.

**Comment by ryanwinchester** [comment]
I will take a look on the weekend.

The master branch has app_id, If you want to use the 2015_2 endpoint.

https://github.com/ryanwinchester/netsuite-php/blob/master/src/NetSuiteClient.php#L60

**Comment by ryanwinchester** [comment]
sorry haven't had time to go through this

**Comment by ctrogers** [comment]
No problem.  I forked the repo and have created a local repo.  I modified the local repo to meet our needs for token authentication.

This issue can be considered closed.  Thanks for your help.

**Comment by ryanwinchester** [comment]
> Thanks for your help.

Is that sarcasm? 😅

**Comment by ctrogers** [comment]
No, just being polite. :grinning:
