### ISSUE TITLE
Other Examples?

### ISSUE THREAD

**Issue by nbyloff** [ryanwinchester/netsuite-php#9]
I realize that isn't the goal of this repo, but documentation for this API is severly lacking online. I can manage customer records just fine starting from your basic example. Have you ever done anything else? I was looking at integrating with the calendar plugin in netsuite. Figured I would need to use the CalendarEvent class, but not sure where to start.

**Comment by ryanwinchester** [comment]
I haven't really used it for much more than customer records and sales order stuff.

And figuring it out has been pretty much trial and error for me too 🎱 

Netsuite is not fun to work with...

**Comment by ryanwinchester** [comment]
Helpful Links

- [Schema browser](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2016_1/schema/record/account.html)
- [Original examples with a clone of the official PHP Toolkit](https://github.com/vegasje/netsuite-toolkit-php/tree/master/samples)

**Comment by nbyloff** [comment]
Haven't seen that schema browser before; extremely helpful thanks. Once I figure out calendar examples, I can make a PR to add extra examples if you like. It couldn't hurt to have a better starting point for the few of us.

**Comment by ryanwinchester** [comment]
Yeah we could make a docs dir and put some stuff in there
